package com.m391.quiz.utils

import android.provider.MediaStore

object Statics {
    const val ONE_MEGABYTE: Long = 1024 * 1024
    const val CODE_SENT = "Code Sent"
    const val EMPTY_OTP = "Please Enter OTP"
    const val SUCCESSFUL_LOGIN = "Successful Login"
    const val INVALID_CODE = "Wrong OTP"
    const val RESPONSE_SUCCESS = "Success"
    const val RESPONSE_INVALID_REQUEST = "Invalid Request"
    const val RESPONSE_SMS_LIMIT_EXCEEDED = "SMS Limit Exceeded"
    const val RESPONSE_RECAPTCHA_WITH_NULL_ACTIVITY = "reCAPTCHA With Null Activity"
    const val EMPTY_PHONE_NUMBER = "Please Enter Yor Phone"
    const val INVALID_PHONE_NUMBER = "Invalid Phone Number"
    const val NOT_COMPLETE_OTP = "Complete OTP Codes"
    const val RESPONSE_ERROR = "Error"
    const val TYPE_STUDENT = "student"
    const val TYPE_TEACHER = "teacher"
    const val STUDENTS = "students"
    const val TEACHERS = "teachers"
    const val FIRST_NAME = "first_name"
    const val LAST_NAME = "last_name"
    const val UID = "uid"
    const val ACADEMIC_YEAR = "academic_year"
    const val ACADEMIC_YEARS = "academic_years"
    const val ACADEMIC_SUBJECTS = "academic_subject"
    const val PROFILE_IMAGE_URI = "profile_image_uri"
    const val PROFILE_IMAGE_PATH = "profile_image_path"
    const val DATE_OF_BARTH = "date_of_barth"
    const val VALID_DATA = "Valid Data"
    const val EMPTY_FIRST_NAME_LAST_NAME = "Please, Complete Your Name"
    const val EMPTY_PROFILE_IMAGE = "Please, Choose Your Profile Image"
    const val EMPTY_ACADEMIC_YEAR = "Please, Select Your Academic Year"
    const val EMPTY_ACADEMIC_YEARS = "Please, Select Your Academic Years"
    const val EMPTY_ACADEMIC_SUBJECTS = "Please, Select Your Academic Subjects"
    const val EMPTY_DATE_OF_BARTH = "Please, Select Your Date Of Barth"

    const val EMPTY_QUIZ_PLACEHOLDER_IMAGE = "Please, Choose Quiz Placeholder"
    const val EMPTY_QUIZ_ACADEMIC_YEAR = "Please, Select Quiz Academic Year"
    const val EMPTY_QUIZ_ACADEMIC_SUBJECTS = "Please, Select Quiz Academic Subject"
    const val EMPTY_QUIZ_DURATION = "Please, Select Quiz Duration"
    const val EMPTY_QUIZ_DESCRIPTION = "Please, Enter Quiz Description"

    const val EMPTY_QUESTION_HEADER = "Please, Enter Question Header"
    const val EMPTY_QUESTION_BODY = "Please, Enter Question Body Text Or Image"
    const val EMPTY_QUESTION_TYPE = "Please, Choose Question Type"
    const val EMPTY_QUESTION_SCORE = "Please , Enter Question Score"
    const val INVALID_QUESTION_SCORE = "Question Score Must Be More Than 0"
    const val EMPTY_ESSAY_ANSWER = "Please, Choose Essay Answer Body"
    const val EMPTY_MCQ_FIRST_CHOICE = "Please ,Enter First Answer Text Or Image"
    const val EMPTY_MCQ_SECOND_CHOICE = "Please ,Enter Second Answer Text Or Image"
    const val EMPTY_MCQ_THIRD_CHOICE = "Please ,Enter Third Answer Text Or Image"
    const val EMPTY_MCQ_FOURTH_CHOICE = "Please ,Enter Fourth Answer Text Or Image"

}