package com.m391.quiz.utils

object Statics {
    const val ONE_MEGABYTE: Long = 1024 * 1024
    const val CODE_SENT = "Code Sent"
    const val EMPTY_OTP = "Please Enter OTP"
    const val SUCCESSFUL_LOGIN = "Successful Login"
    const val INVALID_CODE = "Wrong OTP"
    const val RESPONSE_SUCCESS = "Success"
    const val RESPONSE_INVALID_REQUEST = "Invalid Request"
    const val RESPONSE_SMS_LIMIT_EXCEEDED = "SMS Limit Exceeded"
    const val RESPONSE_RECAPTCHA_WITH_NULL_ACTIVITY = "reCAPTCHA With Null Activity"
    const val EMPTY_PHONE_NUMBER = "Please Enter Yor Phone"
    const val INVALID_PHONE_NUMBER = "Invalid Phone Number"
    const val NOT_COMPLETE_OTP = "Complete OTP Codes"
    const val RESPONSE_ERROR = "Error"
    const val TYPE_STUDENT = "student"
    const val TYPE_TEACHER = "teacher"
    const val STUDENTS = "students"
    const val TEACHERS = "teachers"
    const val FIRST_NAME = "first_name"
    const val LAST_NAME = "last_name"
    const val UID = "uid"
    const val ACADEMIC_YEAR = "academic_year"
    const val ACADEMIC_YEARS = "academic_years"
    const val ACADEMIC_SUBJECTS = "academic_subject"
    const val PROFILE_IMAGE_URI = "profile_image_uri"
    const val PROFILE_IMAGE_PATH = "profile_image_path"
    const val DATE_OF_BARTH = "date_of_barth"
    const val VALID_DATA = "Valid Data"
    const val EMPTY_FIRST_NAME_LAST_NAME = "Please, Complete Your Name"
    const val EMPTY_PROFILE_IMAGE = "Please, Choose Your Profile Image"
    const val EMPTY_ACADEMIC_YEAR = "Please, Select Your Academic Year"
    const val EMPTY_ACADEMIC_YEARS = "Please, Select Your Academic Years"
    const val EMPTY_ACADEMIC_SUBJECTS = "Please, Select Your Academic Subjects"
    const val EMPTY_DATE_OF_BARTH = "Please, Select Your Date Of Barth"

    const val EMPTY_QUIZ_PLACEHOLDER_IMAGE = "Please, Choose Quiz Placeholder"
    const val EMPTY_QUIZ_ACADEMIC_YEAR = "Please, Select Quiz Academic Year"
    const val EMPTY_QUIZ_ACADEMIC_SUBJECTS = "Please, Select Quiz Academic Subject"
    const val EMPTY_QUIZ_DURATION = "Please, Select Quiz Duration"
    const val EMPTY_QUIZ_DESCRIPTION = "Please, Enter Quiz Description"

    const val EMPTY_QUESTION_HEADER = "Please, Enter Question Header"
    const val EMPTY_QUESTION_BODY = "Please, Enter Question Body Text Or Image"
    const val EMPTY_QUESTION_TYPE = "Please, Choose Question Type"
    const val EMPTY_QUESTION_SCORE = "Please , Enter Question Score"
    const val INVALID_QUESTION_SCORE = "Question Score Must Be More Than 0"
    const val EMPTY_ESSAY_ANSWER = "Please, Choose Essay Answer Body"
    const val EMPTY_MCQ_FIRST_CHOICE = "Please ,Enter First Answer Text Or Image"
    const val EMPTY_MCQ_SECOND_CHOICE = "Please ,Enter Second Answer Text Or Image"
    const val EMPTY_MCQ_THIRD_CHOICE = "Please ,Enter Third Answer Text Or Image"
    const val EMPTY_MCQ_FOURTH_CHOICE = "Please ,Enter Fourth Answer Text Or Image"

    const val QUIZZES = "quizzes"
    const val QUIZ = "Quiz"
    const val Question = "Question"
    const val QUESTION_LOWER_CASE = "question"
    const val QUESTIONS = "questions"
    const val QUIZ_ID = "quiz_id"
    const val QUIZ_DURATION = "quiz_duration"
    const val QUIZ_CREATOR = "quiz_creator"
    const val QUIZ_IMAGE_URL = "quiz_image_url"
    const val QUIZ_IMAGE_PATH = "quiz_image_path"
    const val QUIZ_ACADEMIC_YEAR = "quiz_academic_year"
    const val QUIZ_SUBJECT = "quiz_subject"
    const val QUIZ_CREATION_TIME = "quiz_creation_time"
    const val QUIZ_DESCRIPTION = "quiz_description"
    const val QUIZ_TITLE = "quiz_title"
    const val QUIZ_SCORE = "quiz_score"
    const val EMPTY_QUIZ_QUESTION = "Quiz Must Have At Least One Question"

    const val QUESTION_HEADER_TEXT = "question_header_text"
    const val QUESTION_BODY_TEXT = "question_body_text"
    const val QUESTION_BODY_IMAGE_URL = "question_body_image_url"
    const val QUESTION_BODY_IMAGE_PATH = "question_body_image_path"
    const val ANSWER_TYPE = "answer_type"
    const val ANSWER_BODY_TEXT = "answer_body_text"
    const val ANSWER_BODY_IMAGE = "answer_body_image"
    const val ANSWER_FIRST_CHOICE_TEXT = "answer_first_choice_text"
    const val ANSWER_FIRST_CHOICE_IMAGE_URL = "answer_first_choice_image_url"
    const val ANSWER_FIRST_CHOICE_IMAGE_PATH = "answer_first_choice_image_path"

    const val ANSWER_SECOND_CHOICE_TEXT = "answer_second_choice_text"
    const val ANSWER_SECOND_CHOICE_IMAGE_URL = "answer_second_choice_image_url"
    const val ANSWER_SECOND_CHOICE_IMAGE_PATH = "answer_second_choice_image_path"

    const val ANSWER_THIRD_CHOICE_TEXT = "answer_third_choice_text"
    const val ANSWER_THIRD_CHOICE_IMAGE_URL = "answer_third_choice_image_url"
    const val ANSWER_THIRD_CHOICE_IMAGE_PATH = "answer_third_choice_image_path"

    const val ANSWER_FOURTH_CHOICE_TEXT = "answer_fourth_choice_text"
    const val ANSWER_FOURTH_CHOICE_IMAGE_URL = "answer_fourth_choice_image_url"
    const val ANSWER_FOURTH_CHOICE_IMAGE_PATH = "answer_fourth_choice_image_path"

    const val QUESTION_SCORE = "question_score"
    const val QUESTION_ID = "question_id"
    const val SOLUTIONS = "solutions"

    const val SOLUTION_TEXT = "solution_text"
    const val SOLUTION_IMAGE_URL = "solution_image_url"
    const val SOLUTION_IMAGE_PATH = "solution_image_path"
    const val SOLUTION_MCQ = "mcq_solution"

    const val QUIZZES_SOLVERS = "quizzes_solvers"
    const val SOLVER_ERROR_RESPONSE = "Already Solved This Quiz"
    const val START_TIME = "start_time"
    const val SOLVER_SUCCESS_RESPONSE = "Quiz Started"

    const val SHOW_QUESTION_ERROR = "Start Quiz First To Show Question"

    const val MCQ_ANSWER_ERROR = "You Must Choose Answer"
    const val ESSAY_ANSWER_ERROR = "You Must Enter Essay Answer"
    const val SOLUTION_VALIDATION_SUCCESS = "Success Validation"

    const val MCQ_FIRST = "First"
    const val MCQ_SECOND = "Second"
    const val MCQ_THIRD = "Third"
    const val MCQ_FOURTH = "Fourth"
    const val BODY_IMAGE_RESTED = "Answer Image Rested"
    const val BODY_IMAGE_SELECTED = "Answer Image Selected"
    const val QUIZ_TIME_OUT = "Quiz Time Out"
    const val QUIZ_SOLVER = "quiz_solver"

    const val SCORE_EMPTY_RESPONSE_ERROR = "You Must Enter Answer Score"
    const val SCORE_VALUE_RESPONSE_ERROR = "Answer Score Must be less than or equal Question Score"

    const val STUDENT_SCORE = "student_Score"
    const val ANSWER_COMMENT = "answer_comment"
    const val STUDENT_QUIZ_TOTAL_SCORE = "student_total_score"
    const val QUIZZES_SCORES = "quizzes_scores"

    const val STUDENTS_SOLVED_QUIZZES = "student_solved_quizzes"

    const val STUDENT_SOLVED_QUIZ = "student_solved_quiz"
    const val STUDENT_UNSOLVED_QUIZ = "student_unsolved_quiz"


}